### ISSUE TITLE
安装最新版报错

### ISSUE THREAD

**Issue by 153264** [hairyf/overlays#44]
X [ERROR] No matching export in "../../node_modules/.pnpm/registry.npmmirror.com+vue-demi@0.14.1_vue@3.3.2/node_modules/vue-demi/lib/index.mjs" for import "useModel"

    ../../node_modules/.pnpm/registry.npmmirror.com+@overlays+vue@0.4.4/node_modules/@overlays/vue/dist/index.js:8:57:
      8 │ import { getCurrentInstance, inject, onMounted, provide, useModel } from "vue-demi";
        ╵                                                          ~~~~~~~~

20:32:47 [vite] error while updating dependencies:
Error: Build failed with 1 error:
../../node_modules/.pnpm/registry.npmmirror.com+@overlays+vue@0.4.4/node_modules/@overlays/vue/dist/index.js:8:57: ERROR: No matching export in "../../node_modules/.pnpm/registry.npmmirror.com+vue-demi@0.14.1_vue@3.3.2/node_modules/vue-demi/lib/index.mjs" for import "useModel"
    at failureErrorWithLog (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1636:15)
    at \web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1046:7)
    at \web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:1057:54)
    at handleRequest (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:723:19)
    at handleIncomingPacket (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:745:7)
    at Socket.readFromStdout (\web\node_modules\.pnpm\esbuild@0.17.13\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by 153264** [comment]
看了一下`pnpm view @overlays/vue versions` 0.4.4版本，上一个版本是0.4.2 
回退到`0.4.2`能正常运行

**Comment by hairyf** [comment]
0.4.4 升级 vue@3.3.2，废弃 @vueuse/core 的 `useModel`，如果 vue 版本是 3.3.2 以下，请使用 0.4.2 版本
